[package]
name = "anon-claim-verifier"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
ultrazk-soroban-verifier = { path = "../../crates/ultrazk-soroban-verifier" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
